name: Publish

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.1

      - name: Cache dependencies
        uses: actions/cache@v2
        id: pnpm-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Prepare worker
        run: pnpm worker

      - name: Publish project
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
